#!/usr/bin/expect -f
set username [lindex $argv 0];
set password [lindex $argv 1];
set ip [lindex $argv 2];
set port [lindex $argv 3];

spawn ssh -p $port $username@$ip
expect "assword:"
send "$password\r"
expect "#"
send "rm -Rf luke \r"
expect "#"
send "wget --quiet -c https://raw.githubusercontent.com/joshuacox/mkcloudatcost/master/luke\r"
expect "#"
send "/bin/bash luke \r"
expect "#"
send "exit \r"
