#!/usr/bin/expect -f
set username [lindex $argv 0];
set password [lindex $argv 1];
set ip [lindex $argv 2];
set port [lindex $argv 3];

spawn ssh -p $port $username@$ip
expect "assword:"
send "$password\r"
expect "#"
send "mkdir -p ~/.ssh \r"
expect "#"
send "chmod 600 ~/.ssh \r"
expect "#"
send "wget https://raw.githubusercontent.com/Thalhalla/keys/master/addus.sh \r"
expect "#"
send "bash addus.sh \r"
expect "#"
send "exit \r"
