#!/bin/bash
echo 'deb http://httpredir.debian.org/debian jessie main contrib non-free'> /etc/apt/sources.list
cat /etc/apt/sources.list
echo 'fuck you apt'

apt-get update -yqq

cd /tmp
wget -c https://raw.githubusercontent.com/joshuacox/mkcloudatcost/master/installcurl.sh
installcurl () {
  bash /tmp/installcurl.sh
}
COUNTZERO=0
while [ $COUNTZERO -lt 40  ]
do
  if [ ! -f /usr/bin/curl ]
    then installcurl
  fi
  COUNTZERO=$[$COUNTZERO+1]
done
